%my_first_tex.tex
\documentclass{article}


\begin{document}

\begin{abstract}
I want to tell you that this is only an abstract.
\end{abstract}

\tableofcontents

\title{THE FIRST COPY OF A LATEX TEST OUTPUT PAPER}
\author{Kai Sun}
\date{\today}
\maketitle

\part{}
A long time ago there was a whale.

\section{}
I know this is right, huh. We are going to first initiate a chapter. Then things will get tricky.

\subsection{}
Then comes the second chapter. It is less tricky, less intimidating, but nonetheless, sublime in its deepest vault. How could you not admire it?

\subsubsection*{}
This is a subsubsection. Who came up with this idea? How many "subs" will there be legitimately?

\paragraph{}
This is paragraph 1.

\subparagraph{}
And this is a tiny tiny subparagraph.

\section{}
Now let's start with a second section.

\paragraph{}
And the paragraph can be very long and repetitive. And the paragraph can be very long and repetitive. And the paragraph can be very long and repetitive. And the paragraph can be very long and repetitive. And the paragraph can be very long and repetitive. And the paragraph can be very long and repetitive. And the paragraph can be very long and repetitive. And the paragraph can be very long and repetitive.

\part{}
In the end, the whale died.

\section{}
Can we make sections work properly? I am testing here.

\part{THE PLAYGROUND}
Now this is Part 3 where serious word maneuvering will begin.

\subsection{}
A strangely placed subsection.

\paragraph{}
First, here is a representation of all the 26 characters: abcdefghijklmnopqrstuvwxyz

\section{Characters}

\subsection{Inserting Characters}

\paragraph{}
Below is a list of characters that need special entry.

\paragraph{}
\# \$ \^  \& \_ \{ \} \~ \%

\paragraph{}
The character "\textbackslash" will  have to be inserted by "\textbackslash textbackslash"
\\
"\textbackslash\textbackslash" is used for line changing.

\paragraph{}
For more characters, please refer to the list by Scott Pakin.

\paragraph{}

\end{document}